const create_progress_bar = require("./create_progress_bar");
const log_info = require("./log_info");
const snooze = require("./snooze");
const newline = require("./newline");

async function delete_old_events(remaining_events, email, calendar_client) {
  log_info("Removing leftover events from Google Calendar", 1);
  // Remove google calendar events ~made by this script~ that are no longer in the user's ical feed
  progress_bar = create_progress_bar();
  progress_bar.start(Object.keys(remaining_events).length, 0);

  for (const [key, gcal_event] of Object.entries(remaining_events)) {
    // Only delete events that are auto-generated by this script
    if (gcal_event?.description?.includes("AUTOGENERATED by Westtown AutoCal")) {
      log_info(`Event: ${gcal_event.summary}`, 2, (extra = gcal_event));
      log_info("Event was auto-generated by this script; removing...", 3);
      // Pause each iteration to avoid rate limiting
      await snooze(500);
      calendar_client.events.delete({
        calendarId: email,
        eventId: gcal_event.id,
      });
    } else {
      log_info(`Event info was redacted for privacy`, 2);
      log_info("Event not generated by this script; skipping", 3);
    }
    // Update progress bar
    newline(1);
    progress_bar.increment();
    newline(1);
  }
}

module.exports = delete_old_events;
